### ISSUE TITLE
sourceMap 不生效

### ISSUE THREAD

**Issue by phzzy** [Geequlim/puerts-starter-kit#13]
我直接clone下来测了一下，也是无法生效的，输出的日志只能定位到 mjs 的行数，无法订到 ts 的行数
请问这个是哪里出了问题吗？

> 已启动 JavaScript 虚拟机 node v16.16.0
>     at new JavaScriptApplication (puerts-starter-kit-master/Assets/PuertsKit/Resources/scripts/bundle.mjs:23:13 )
>     at main (puerts-starter-kit-master/Assets/PuertsKit/Resources/scripts/bundle.mjs:120:10 )

还有文档里写，需要执行 npm run webapi:publish，但这条命令已经在 tsconfig.ts 里不存在了

**Comment by phzzy** [comment]
不好意思，已经可以定位到具体的 ts 行数了
不过文档里那个 npm run webapi:publish 可以改改

**Comment by phzzy** [comment]
可能和 Puerts 的版本有有关，我是用的2.0.0pre3的版本。 我把demo项目，去掉package里的puerts，然后把2.0.0考进去，sourceMap也会失效

**Comment by Geequlim** [comment]
已修正
