### ISSUE TITLE
mac run webapi:publish get error, Cannot find module 'csharp'

### ISSUE THREAD

**Issue by ankyecc** [Geequlim/puerts-starter-kit#2]
(base) ➜  Scripts git:(master) ✗ npm run webapi:publish

> @ webapi:publish /Users/admin/work/project/puerts-starter-kit/Scripts
> webpack --config webpack.config.js --env.production --env.entry=webapi

Compile config: { production: true, entry: 'webapi' }
Hash: beeb7978ba7a8c62d4de
Version: webpack 4.44.2
Time: 1597ms
Built at: 01/29/2021 2:02:58 PM
 2 assets
Entrypoint main = webapi.js webapi.js.map
[0] external "csharp" 42 bytes {0} [built]
[2] external "puerts" 42 bytes {0} [built]
[3] ./src/addons/webapi/index.unity.ts + 18 modules 70.9 KiB {0} [built]
    | ./src/addons/webapi/index.unity.ts 457 bytes [built]
    | ./src/addons/webapi/console.unity.ts 3.08 KiB [built]
    | ./src/addons/webapi/animationframe.ts 513 bytes [built]
    | ./src/addons/webapi/event.ts 10.7 KiB [built]
    | ./src/addons/webapi/timer.ts 1.95 KiB [built]
    | ./src/addons/webapi/performance.ts 3.66 KiB [built]
    | ./src/addons/webapi/misc.unity.ts 550 bytes [built]
    | ./src/addons/webapi/storage.unity.ts 1.32 KiB [built]
    | ./src/addons/webapi/xhr/xhr.unity.ts 7.75 KiB [built]
    | ./src/addons/webapi/index.common.ts 896 bytes [built]
    | ./src/addons/webapi/storage.ts 2.48 KiB [built]
    | ./src/addons/webapi/xhr/url.ts 561 bytes [built]
    | ./src/addons/webapi/xhr/thirdpart/mimetype/mime-type.js 4.96 KiB [built]
    | ./src/addons/webapi/xhr/xhr.common.ts 9.87 KiB [built]
    | ./src/addons/webapi/xhr/thirdpart/url-parser/url-parser.js 12.4 KiB [built]
    |     + 4 hidden modules
    + 1 hidden module

ERROR in /Users/admin/work/project/puerts-starter-kit/Scripts/src/addons/webapi/console.unity.ts
[tsl] ERROR in /Users/admin/work/project/puerts-starter-kit/Scripts/src/addons/webapi/console.unity.ts(1,42)
      TS2307: Cannot find module 'csharp' or its corresponding type declarations.

ERROR in /Users/admin/work/project/puerts-starter-kit/Scripts/src/addons/webapi/misc.unity.ts
[tsl] ERROR in /Users/admin/work/project/puerts-starter-kit/Scripts/src/addons/webapi/misc.unity.ts(1,24)
      TS2307: Cannot find module 'csharp' or its corresponding type declarations.

ERROR in /Users/admin/work/project/puerts-starter-kit/Scripts/src/addons/webapi/xhr/xhr.unity.ts
[tsl] ERROR in /Users/admin/work/project/puerts-starter-kit/Scripts/src/addons/webapi/xhr/xhr.unity.ts(5,37)
      TS2307: Cannot find module 'csharp' or its corresponding type declarations.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ webapi:publish: `webpack --config webpack.config.js --env.production --env.entry=webapi`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @ webapi:publish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/admin/.npm/_logs/2021-01-29T06_02_58_139Z-debug.log

**Comment by ankyecc** [comment]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node@10/10.23.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'webapi:publish' ]
2 info using npm@6.14.8
3 info using node@v10.23.0
4 verbose run-script [ 'prewebapi:publish', 'webapi:publish', 'postwebapi:publish' ]
5 info lifecycle @~prewebapi:publish: @
6 info lifecycle @~webapi:publish: @
7 verbose lifecycle @~webapi:publish: unsafe-perm in lifecycle true
8 verbose lifecycle @~webapi:publish: PATH: /usr/local/Cellar/node@10/10.23.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/admin/work/project/puerts-starter-kit/Scripts/node_modules/.bin:/usr/local/sbin:/Users/admin/work/flutter/bin:/usr/local/opt/apr/bin:/usr/local/opt/apr-util/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Wireshark.app/Contents/MacOS:/Users/admin/anaconda3/bin:/Users/admin/anaconda3/condabin:/usr/local/sbin:/Users/admin/work/flutter/bin:/usr/local/opt/apr/bin:/usr/local/opt/apr-util/bin:/Users/admin/go/bin:/usr/local/opt/go/libexec/bin:/usr/local/Cellar/curl-openssl/7.73.0/bin:/Users/admin/Library/Android/sdk/platform-tools:/Users/admin/Library/Android/sdk/emulator:/Users/admin/Library/Android/sdk/tools:/Users/admin/Library/Android/sdk/tools/bin:/Users/admin/.composer/vendor/bin:/Users/admin/go/bin:/usr/local/opt/go/libexec/bin:/usr/local/Cellar/curl-openssl/7.73.0/bin:/Users/admin/Library/Android/sdk/platform-tools:/Users/admin/Library/Android/sdk/emulator:/Users/admin/Library/Android/sdk/tools:/Users/admin/Library/Android/sdk/tools/bin:/Users/admin/Library/Android/sdk/platform-tools:/Users/admin/Library/Android/sdk/platform-tools:/Users/admin/.composer/vendor/bin:/bin
9 verbose lifecycle @~webapi:publish: CWD: /Users/admin/work/project/puerts-starter-kit/Scripts
10 silly lifecycle @~webapi:publish: Args: [ '-c',
10 silly lifecycle   'webpack --config webpack.config.js --env.production --env.entry=webapi' ]
11 silly lifecycle @~webapi:publish: Returned: code: 2  signal: null
12 info lifecycle @~webapi:publish: Failed to exec webapi:publish script
13 verbose stack Error: @ webapi:publish: `webpack --config webpack.config.js --env.production --env.entry=webapi`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/Cellar/node@10/10.23.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/Cellar/node@10/10.23.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid @
15 verbose cwd /Users/admin/work/project/puerts-starter-kit/Scripts
16 verbose Darwin 19.6.0
17 verbose argv "/usr/local/Cellar/node@10/10.23.0/bin/node" "/usr/local/bin/npm" "run" "webapi:publish"
18 verbose node v10.23.0
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 2
22 error @ webapi:publish: `webpack --config webpack.config.js --env.production --env.entry=webapi`
22 error Exit status 2
23 error Failed at the @ webapi:publish script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]

**Comment by Geequlim** [comment]
用 puerts 的 unity 插件生成 ts 声明文件
