### ISSUE TITLE
运行时unity 报红Curl error

### ISSUE THREAD

**Issue by CoderMzx** [Geequlim/puerts-starter-kit#7]
`Curl error 1: Protocol "webpack-internal" not supported or disabled in libcurl`
这个是Unity报红的错误,正常使用框架按照说明安装后运行就报,不是很清楚因为什么引起了这个

**Comment by Geequlim** [comment]
新版使用webpack5进行构建，更换了sourcemap的生成方式。更新到最新的版本尝试一下还有此问题吗？

**Comment by CoderMzx** [comment]
报红的问题已经不出现了
